@echo off
echo Killing all Node.js processes...
taskkill /f /im node.exe 2>nul
echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul
echo Starting server...
cd /d "C:\Users\Game Centar\LYNX"
npm run dev 